[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
colored = "3.1.1"
num-integer = "0.1.46"
shared = { version = "0.1.0", path = "../../shared" }
