[package]
name = "day19"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
priority-queue = "2.7.0"
regex = "1.12.2"
strum = "0.27.2"
strum_macros = "0.27.2"
