[package]
name = "day24"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
colored = "3.1.1"
priority-queue = "2.7.0"
shared = { version = "0.1.0", path = "../../shared" }
