[package]
name = "day12"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
colored = "3.1.1"
num-integer = "0.1.46"
regex = "1.12.3"
shared = { version = "0.1.0", path = "../../shared" }
