[package]
name = "day15"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
colored = "3.1.1"
intcode = { version = "0.1.0", path = "../intcode" }
rand = "0.9.2"
shared = { version = "0.1.0", path = "../../shared" }
