[package]
name = "day7"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
intcode = { version = "0.1.0", path = "../intcode" }
itertools = "0.14.0"
